export const GET_ALL_SURVEYS_REQUEST = 'GET_ALL_SURVEYS_REQUEST';
export const GET_ALL_SURVEYS_SUCCESS = 'GET_ALL_SURVEYS_SUCCESS';
export const GET_ALL_SURVEYS_ERROR = 'GET_ALL_SURVEYS_ERROR';

export const GET_SURVEY_REQUEST = 'GET_SURVEY_REQUEST';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const GET_SURVEY_ERROR = 'GET_SURVEY_ERROR';

export const POST_SURVEY_REQUEST = 'POST_SURVEY_REQUEST';
export const POST_SURVEY_SUCCESS = 'POST_SURVEY_SUCCESS';
export const POST_SURVEY_ERROR = 'POST_SURVEY_ERROR';

export const GET_SURVEY_RESPONSES_REQUEST = 'GET_SURVEY_RESPONSES_REQUEST';
export const GET_SURVEY_RESPONSES_SUCCESS = 'GET_SURVEY_RESPONSES_SUCCESS';
export const GET_SURVEY_RESPONSES_ERROR = 'GET_SURVEY_RESPONSES_ERROR';

export const RESPOND_SURVEY_REQUEST = 'RESPOND_SURVEY_REQUEST';
export const RESPOND_SURVEY_SUCCESS = 'RESPOND_SURVEY_SUCCESS';
export const RESPOND_SURVEY_ERROR = 'RESPOND_SURVEY_ERROR';

