export const GET_ALL_SURVEYS_REQUEST = 'GET_ALL_SURVEYS_REQUEST';
export const GET_ALL_SURVEYS_SUCCESS = 'GET_ALL_SURVEYS_SUCCESS';

export const GET_SURVEY_REQUEST = 'GET_SURVEY_REQUEST';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';

export const GET_SURVEY_RESPONSES_SUCCESS = 'GET_SURVEY_RESPONSES_SUCCESS';
